[variables]
NITRO_PRESET = "node-server"
NODE_ENV = "production"
HOST = "0.0.0.0"
PORT = "3000"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node .output/server/index.mjs"
